# Data Cleaning: Healthcare Dataset

This notebook handles the initial data cleaning and preprocessing for the healthcare analytics project. We will address text standardization, data type conversion, and missing values.

In [5]:
import pandas as pd
import numpy as np

# Load the raw data
# Assuming this notebook is in the 'notebooks' folder and data is in 'data/raw'

df = pd.read_csv('../data/raw/healthcare_dataset.csv')

df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

## 1. Text Standardization
Cleaning up the formatting of string columns like `Name`.

In [6]:
# Standardize the 'Name' column to title case
df['Name'] = df['Name'].str.title()

# Display changes
df[['Name']].head()

            Name
0  Bobby Jackson
1   Leslie Terry
2    Danny Smith
3   Andrew Watts
4  Adrienne Bell

## 2. Date Type Conversion
Converting `Date of Admission` and `Discharge Date` to datetime objects.

In [7]:
df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])

# Create a new feature: Length of Stay
df['Length of Stay'] = (df['Discharge Date'] - df['Date of Admission']).dt.days

df[['Date of Admission', 'Discharge Date', 'Length of Stay']].head()

  Date of Admission Discharge Date  Length of Stay
0        2024-01-31     2024-02-02               2
1        2019-08-20     2019-08-26               6
2        2022-09-22     2022-10-07              15
3        2020-11-18     2020-12-18              30
4        2022-09-19     2022-10-09              20

## 3. Save Processed Data
Exporting the cleaned dataset so it can be used for EDA and Modeling.

In [8]:
df.to_csv('../data/processed/cleaned_healthcare_dataset.csv', index=False)
print("Data cleaning steps complete. Ready for export.")

Data cleaning steps complete. Ready for export.